{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neurobagel.secretName" . }}
  labels:
    {{- include "neurobagel.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.keys.admin }}: {{ required "secrets.adminPassword is required when secrets.create=true" .Values.secrets.adminPassword | b64enc }}
  {{ .Values.secrets.keys.user }}: {{ required "secrets.userPassword is required when secrets.create=true" .Values.secrets.userPassword | b64enc }}
{{- end }}
