apiVersion: v2
name: neurobagel
description: Kubernetes-native Helm chart for deploying Neurobagel node and portal profiles
type: application
version: 0.1.1
appVersion: "1.16.0"
home: https://github.com/neurobagel/recipes
sources:
  - https://github.com/neurobagel/recipes
keywords:
  - neurobagel
  - helm
  - kubernetes
  - graphdb
  - federation
maintainers:
  - name: neurobagel
    url: https://github.com/neurobagel
